grepping only the YAML and .github folder

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -271,10 +271,10 @@ check_docker:
     - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "develop"'
       when: on_success
   script:
-    - if grep -Rq "hogcern/hog:develop" .; then
-        echo "ERROR. The Docker image 'hogcern/hog:develop' is used in the codebase. Please, change it to 'hogcern/hog:<docker_tag>' before merging into Hog master. This is necessary to ensure that the master branch is always built with the latest stable Docker image. ";
-        echo "You might also need to create the Dockerfile tag in the hog-docker repository. https://gitlab.com/hog-cern/hog-docker";
-        exit 1;
+    - if grep -Rq "hogcern/hog:develop" YAML .github; then
+      echo "ERROR. The Docker image 'hogcern/hog:develop' is used in the codebase. Please, change it to 'hogcern/hog:<docker_tag>' before merging into Hog master. This is necessary to ensure that the master branch is always built with the latest stable Docker image. ";
+      echo "You might also need to create the Dockerfile tag in the hog-docker repository. https://gitlab.com/hog-cern/hog-docker";
+      exit 1;
       fi
   interruptible: true
 
