introducing HOG_FAIL_TIMING variable to make a generate job failing.

diff --git a/.github/workflows/Hog-pull.yml b/.github/workflows/Hog-pull.yml
--- a/.github/workflows/Hog-pull.yml
+++ b/.github/workflows/Hog-pull.yml
@@ -60,6 +60,9 @@ on:
       HOG_SIM_COMPILE_ONLY:
         required: false
         type: string
+      HOG_FAIL_TIMING:
+        required: false
+        type: string
     secrets:
       HOG_PUSH_TOKEN:
         required: true
@@ -393,6 +396,16 @@ jobs:
                   fi;
                   if [[ -f bin/$PROJECT_NAME*/timing_* ]]; then
                     cat bin/$PROJECT_NAME*/timing_* >> note.md;
+                  fi;
+                  if ls bin/$PROJECT_NAME*/timing_error.txt >/dev/null 2>&1; then
+                    if [ ${{ inputs.HOG_FAIL_TIMING}} ]; then
+                      echo "Hog-CI(error) - Project $PROJECT_NAME failed timing constraints. Failing the job as requested.";
+                      echo "Copying the Project folder for debugging purposes inside bin/";
+                      cp -r Projects/ bin/Projects
+                      exit 1;
+                    else
+                      echo "Hog-CI(critical warning) - Project $PROJECT_NAME failed timing constraints.";
+                    fi;
                   fi;
                 fi;
               fi;
diff --git a/YAML/hog-child.yml b/YAML/hog-child.yml
--- a/YAML/hog-child.yml
+++ b/YAML/hog-child.yml
@@ -265,6 +265,14 @@
           if [ -f "$CI_PROJECT_DIR/Projects/$PROJECT_NAME/versions.txt" ]; then
             cp $CI_PROJECT_DIR/Projects/$PROJECT_NAME/versions.txt $CI_PROJECT_DIR/bin/$PROJECT_NAME*/;
           fi;
+          if ls $CI_PROJECT_DIR/bin/$PROJECT_NAME*/timing_error.txt >/dev/null 2>&1; then
+            if [ -n "$HOG_FAIL_TIMING" ] && [ "$HOG_FAIL_TIMING" = '1' ]; then
+              echo "Hog-CI(error) - Project $PROJECT_NAME failed timing constraints. Failing the job as requested.";
+              exit 1;
+            else
+              echo "Hog-CI(critical warning) - Project $PROJECT_NAME failed timing constraints.";
+            fi;
+          fi;
         fi;
         echo "Hog-CI(info) - All done.";
       fi;
